### ISSUE TITLE
Please remove dependency slf4j-simple 

### ISSUE THREAD

**Issue by dmbakker** [liquibase/liquibase-parent-pom#127]
Upgrading to liquibase-db2i version 4.25.1 breaks our unit tests that test logging. That version upgraded the dependency liquibase-parent-pom to 0.3.4 and introduced 2 new dependencies from which slf4j-simple is taking over as our logger but does not work with our testappender. Please make the dependency scope provided or remove it from the pom. I also think you should choose either slf4j-api or slf4j-simple.

**Comment by jandroav** [comment]
Hey @dmbakker we can make it scope provided but it seems the API and its implementation needs to be declared: https://www.slf4j.org/manual.html#projectDep
