### ISSUE TITLE
Dependency on liquibase-commercial should be provided

### ISSUE THREAD

**Issue by meisenla** [liquibase/liquibase-parent-pom#168]
The dependency on liquibase-commercial has no longer the provided scope. Therefore if you use a extension that use the parent-pom, your project will have a dependency on liquibase-commercia, even if you do not use Liquibase Pro. Prior to #152 liquibase-commercial had the  #scope provided.

**Comment by jandroav** [comment]
Fixed in liquibase-parent-pom `0.3.9`. Thanks @meisenla !

It will be available in Maven Central in a few minutes.
